name: packhorse
description: Support for small to medium data manipulation and analysis projects, including numeric and categoric data list-like structures and data frames.
version: 0.6.1
homepage: https://bitbucket.org/ram6ler/packhorse
author: Richard Ambler <rambler@ibwya.net>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  function_tree: ^0.5.0
    #git: https://ram6ler@bitbucket.org/ram6ler/function-tree.git
  normal: ^0.5.1
    #git: https://ram6ler@bitbucket.org/ram6ler/normal.git

dev_dependencies:
  popmark: ^0.1.0

