name: packhorse
description: Support for small to medium data manipulation and analysis projects, either at the server or client side.
version: 0.7.0
homepage: https://github.com/ram6ler/packhorse

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  function_tree: ^0.9.0
  normal: ^0.7.0

